# Generated by Django 4.1.5 on 2023-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
